# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local64/bin/cmake

# The command to remove a file.
RM = /usr/local64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/akilan/CHERI-FLEXPOINTER

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/akilan/CHERI-FLEXPOINTER

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akilan/CHERI-FLEXPOINTER/CMakeFiles /home/akilan/CHERI-FLEXPOINTER//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akilan/CHERI-FLEXPOINTER/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jemalloc

# Build rule for target.
jemalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jemalloc
.PHONY : jemalloc

# fast build rule for target.
jemalloc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/build
.PHONY : jemalloc/fast

# target to build an object file
jemalloc/src/arena.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/arena.o
.PHONY : jemalloc/src/arena.o

# target to preprocess a source file
jemalloc/src/arena.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/arena.i
.PHONY : jemalloc/src/arena.i

# target to generate assembly for a file
jemalloc/src/arena.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/arena.s
.PHONY : jemalloc/src/arena.s

# target to build an object file
jemalloc/src/background_thread.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/background_thread.o
.PHONY : jemalloc/src/background_thread.o

# target to preprocess a source file
jemalloc/src/background_thread.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/background_thread.i
.PHONY : jemalloc/src/background_thread.i

# target to generate assembly for a file
jemalloc/src/background_thread.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/background_thread.s
.PHONY : jemalloc/src/background_thread.s

# target to build an object file
jemalloc/src/base.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/base.o
.PHONY : jemalloc/src/base.o

# target to preprocess a source file
jemalloc/src/base.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/base.i
.PHONY : jemalloc/src/base.i

# target to generate assembly for a file
jemalloc/src/base.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/base.s
.PHONY : jemalloc/src/base.s

# target to build an object file
jemalloc/src/bin.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/bin.o
.PHONY : jemalloc/src/bin.o

# target to preprocess a source file
jemalloc/src/bin.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/bin.i
.PHONY : jemalloc/src/bin.i

# target to generate assembly for a file
jemalloc/src/bin.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/bin.s
.PHONY : jemalloc/src/bin.s

# target to build an object file
jemalloc/src/bitmap.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/bitmap.o
.PHONY : jemalloc/src/bitmap.o

# target to preprocess a source file
jemalloc/src/bitmap.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/bitmap.i
.PHONY : jemalloc/src/bitmap.i

# target to generate assembly for a file
jemalloc/src/bitmap.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/bitmap.s
.PHONY : jemalloc/src/bitmap.s

# target to build an object file
jemalloc/src/ckh.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ckh.o
.PHONY : jemalloc/src/ckh.o

# target to preprocess a source file
jemalloc/src/ckh.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ckh.i
.PHONY : jemalloc/src/ckh.i

# target to generate assembly for a file
jemalloc/src/ckh.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ckh.s
.PHONY : jemalloc/src/ckh.s

# target to build an object file
jemalloc/src/ctl.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ctl.o
.PHONY : jemalloc/src/ctl.o

# target to preprocess a source file
jemalloc/src/ctl.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ctl.i
.PHONY : jemalloc/src/ctl.i

# target to generate assembly for a file
jemalloc/src/ctl.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ctl.s
.PHONY : jemalloc/src/ctl.s

# target to build an object file
jemalloc/src/div.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/div.o
.PHONY : jemalloc/src/div.o

# target to preprocess a source file
jemalloc/src/div.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/div.i
.PHONY : jemalloc/src/div.i

# target to generate assembly for a file
jemalloc/src/div.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/div.s
.PHONY : jemalloc/src/div.s

# target to build an object file
jemalloc/src/extent.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent.o
.PHONY : jemalloc/src/extent.o

# target to preprocess a source file
jemalloc/src/extent.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent.i
.PHONY : jemalloc/src/extent.i

# target to generate assembly for a file
jemalloc/src/extent.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent.s
.PHONY : jemalloc/src/extent.s

# target to build an object file
jemalloc/src/extent_dss.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent_dss.o
.PHONY : jemalloc/src/extent_dss.o

# target to preprocess a source file
jemalloc/src/extent_dss.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent_dss.i
.PHONY : jemalloc/src/extent_dss.i

# target to generate assembly for a file
jemalloc/src/extent_dss.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent_dss.s
.PHONY : jemalloc/src/extent_dss.s

# target to build an object file
jemalloc/src/extent_mmap.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent_mmap.o
.PHONY : jemalloc/src/extent_mmap.o

# target to preprocess a source file
jemalloc/src/extent_mmap.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent_mmap.i
.PHONY : jemalloc/src/extent_mmap.i

# target to generate assembly for a file
jemalloc/src/extent_mmap.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/extent_mmap.s
.PHONY : jemalloc/src/extent_mmap.s

# target to build an object file
jemalloc/src/hash.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/hash.o
.PHONY : jemalloc/src/hash.o

# target to preprocess a source file
jemalloc/src/hash.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/hash.i
.PHONY : jemalloc/src/hash.i

# target to generate assembly for a file
jemalloc/src/hash.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/hash.s
.PHONY : jemalloc/src/hash.s

# target to build an object file
jemalloc/src/hook.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/hook.o
.PHONY : jemalloc/src/hook.o

# target to preprocess a source file
jemalloc/src/hook.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/hook.i
.PHONY : jemalloc/src/hook.i

# target to generate assembly for a file
jemalloc/src/hook.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/hook.s
.PHONY : jemalloc/src/hook.s

# target to build an object file
jemalloc/src/jemalloc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/jemalloc.o
.PHONY : jemalloc/src/jemalloc.o

# target to preprocess a source file
jemalloc/src/jemalloc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/jemalloc.i
.PHONY : jemalloc/src/jemalloc.i

# target to generate assembly for a file
jemalloc/src/jemalloc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/jemalloc.s
.PHONY : jemalloc/src/jemalloc.s

# target to build an object file
jemalloc/src/large.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/large.o
.PHONY : jemalloc/src/large.o

# target to preprocess a source file
jemalloc/src/large.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/large.i
.PHONY : jemalloc/src/large.i

# target to generate assembly for a file
jemalloc/src/large.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/large.s
.PHONY : jemalloc/src/large.s

# target to build an object file
jemalloc/src/log.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/log.o
.PHONY : jemalloc/src/log.o

# target to preprocess a source file
jemalloc/src/log.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/log.i
.PHONY : jemalloc/src/log.i

# target to generate assembly for a file
jemalloc/src/log.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/log.s
.PHONY : jemalloc/src/log.s

# target to build an object file
jemalloc/src/malloc_io.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/malloc_io.o
.PHONY : jemalloc/src/malloc_io.o

# target to preprocess a source file
jemalloc/src/malloc_io.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/malloc_io.i
.PHONY : jemalloc/src/malloc_io.i

# target to generate assembly for a file
jemalloc/src/malloc_io.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/malloc_io.s
.PHONY : jemalloc/src/malloc_io.s

# target to build an object file
jemalloc/src/mutex.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/mutex.o
.PHONY : jemalloc/src/mutex.o

# target to preprocess a source file
jemalloc/src/mutex.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/mutex.i
.PHONY : jemalloc/src/mutex.i

# target to generate assembly for a file
jemalloc/src/mutex.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/mutex.s
.PHONY : jemalloc/src/mutex.s

# target to build an object file
jemalloc/src/mutex_pool.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/mutex_pool.o
.PHONY : jemalloc/src/mutex_pool.o

# target to preprocess a source file
jemalloc/src/mutex_pool.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/mutex_pool.i
.PHONY : jemalloc/src/mutex_pool.i

# target to generate assembly for a file
jemalloc/src/mutex_pool.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/mutex_pool.s
.PHONY : jemalloc/src/mutex_pool.s

# target to build an object file
jemalloc/src/nstime.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/nstime.o
.PHONY : jemalloc/src/nstime.o

# target to preprocess a source file
jemalloc/src/nstime.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/nstime.i
.PHONY : jemalloc/src/nstime.i

# target to generate assembly for a file
jemalloc/src/nstime.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/nstime.s
.PHONY : jemalloc/src/nstime.s

# target to build an object file
jemalloc/src/pages.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/pages.o
.PHONY : jemalloc/src/pages.o

# target to preprocess a source file
jemalloc/src/pages.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/pages.i
.PHONY : jemalloc/src/pages.i

# target to generate assembly for a file
jemalloc/src/pages.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/pages.s
.PHONY : jemalloc/src/pages.s

# target to build an object file
jemalloc/src/prng.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/prng.o
.PHONY : jemalloc/src/prng.o

# target to preprocess a source file
jemalloc/src/prng.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/prng.i
.PHONY : jemalloc/src/prng.i

# target to generate assembly for a file
jemalloc/src/prng.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/prng.s
.PHONY : jemalloc/src/prng.s

# target to build an object file
jemalloc/src/prof.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/prof.o
.PHONY : jemalloc/src/prof.o

# target to preprocess a source file
jemalloc/src/prof.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/prof.i
.PHONY : jemalloc/src/prof.i

# target to generate assembly for a file
jemalloc/src/prof.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/prof.s
.PHONY : jemalloc/src/prof.s

# target to build an object file
jemalloc/src/rtree.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/rtree.o
.PHONY : jemalloc/src/rtree.o

# target to preprocess a source file
jemalloc/src/rtree.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/rtree.i
.PHONY : jemalloc/src/rtree.i

# target to generate assembly for a file
jemalloc/src/rtree.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/rtree.s
.PHONY : jemalloc/src/rtree.s

# target to build an object file
jemalloc/src/stats.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/stats.o
.PHONY : jemalloc/src/stats.o

# target to preprocess a source file
jemalloc/src/stats.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/stats.i
.PHONY : jemalloc/src/stats.i

# target to generate assembly for a file
jemalloc/src/stats.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/stats.s
.PHONY : jemalloc/src/stats.s

# target to build an object file
jemalloc/src/sz.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/sz.o
.PHONY : jemalloc/src/sz.o

# target to preprocess a source file
jemalloc/src/sz.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/sz.i
.PHONY : jemalloc/src/sz.i

# target to generate assembly for a file
jemalloc/src/sz.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/sz.s
.PHONY : jemalloc/src/sz.s

# target to build an object file
jemalloc/src/tcache.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/tcache.o
.PHONY : jemalloc/src/tcache.o

# target to preprocess a source file
jemalloc/src/tcache.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/tcache.i
.PHONY : jemalloc/src/tcache.i

# target to generate assembly for a file
jemalloc/src/tcache.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/tcache.s
.PHONY : jemalloc/src/tcache.s

# target to build an object file
jemalloc/src/ticker.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ticker.o
.PHONY : jemalloc/src/ticker.o

# target to preprocess a source file
jemalloc/src/ticker.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ticker.i
.PHONY : jemalloc/src/ticker.i

# target to generate assembly for a file
jemalloc/src/ticker.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/ticker.s
.PHONY : jemalloc/src/ticker.s

# target to build an object file
jemalloc/src/tsd.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/tsd.o
.PHONY : jemalloc/src/tsd.o

# target to preprocess a source file
jemalloc/src/tsd.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/tsd.i
.PHONY : jemalloc/src/tsd.i

# target to generate assembly for a file
jemalloc/src/tsd.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/tsd.s
.PHONY : jemalloc/src/tsd.s

# target to build an object file
jemalloc/src/witness.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/witness.o
.PHONY : jemalloc/src/witness.o

# target to preprocess a source file
jemalloc/src/witness.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/witness.i
.PHONY : jemalloc/src/witness.i

# target to generate assembly for a file
jemalloc/src/witness.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jemalloc.dir/build.make CMakeFiles/jemalloc.dir/jemalloc/src/witness.s
.PHONY : jemalloc/src/witness.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... jemalloc"
	@echo "... jemalloc/src/arena.o"
	@echo "... jemalloc/src/arena.i"
	@echo "... jemalloc/src/arena.s"
	@echo "... jemalloc/src/background_thread.o"
	@echo "... jemalloc/src/background_thread.i"
	@echo "... jemalloc/src/background_thread.s"
	@echo "... jemalloc/src/base.o"
	@echo "... jemalloc/src/base.i"
	@echo "... jemalloc/src/base.s"
	@echo "... jemalloc/src/bin.o"
	@echo "... jemalloc/src/bin.i"
	@echo "... jemalloc/src/bin.s"
	@echo "... jemalloc/src/bitmap.o"
	@echo "... jemalloc/src/bitmap.i"
	@echo "... jemalloc/src/bitmap.s"
	@echo "... jemalloc/src/ckh.o"
	@echo "... jemalloc/src/ckh.i"
	@echo "... jemalloc/src/ckh.s"
	@echo "... jemalloc/src/ctl.o"
	@echo "... jemalloc/src/ctl.i"
	@echo "... jemalloc/src/ctl.s"
	@echo "... jemalloc/src/div.o"
	@echo "... jemalloc/src/div.i"
	@echo "... jemalloc/src/div.s"
	@echo "... jemalloc/src/extent.o"
	@echo "... jemalloc/src/extent.i"
	@echo "... jemalloc/src/extent.s"
	@echo "... jemalloc/src/extent_dss.o"
	@echo "... jemalloc/src/extent_dss.i"
	@echo "... jemalloc/src/extent_dss.s"
	@echo "... jemalloc/src/extent_mmap.o"
	@echo "... jemalloc/src/extent_mmap.i"
	@echo "... jemalloc/src/extent_mmap.s"
	@echo "... jemalloc/src/hash.o"
	@echo "... jemalloc/src/hash.i"
	@echo "... jemalloc/src/hash.s"
	@echo "... jemalloc/src/hook.o"
	@echo "... jemalloc/src/hook.i"
	@echo "... jemalloc/src/hook.s"
	@echo "... jemalloc/src/jemalloc.o"
	@echo "... jemalloc/src/jemalloc.i"
	@echo "... jemalloc/src/jemalloc.s"
	@echo "... jemalloc/src/large.o"
	@echo "... jemalloc/src/large.i"
	@echo "... jemalloc/src/large.s"
	@echo "... jemalloc/src/log.o"
	@echo "... jemalloc/src/log.i"
	@echo "... jemalloc/src/log.s"
	@echo "... jemalloc/src/malloc_io.o"
	@echo "... jemalloc/src/malloc_io.i"
	@echo "... jemalloc/src/malloc_io.s"
	@echo "... jemalloc/src/mutex.o"
	@echo "... jemalloc/src/mutex.i"
	@echo "... jemalloc/src/mutex.s"
	@echo "... jemalloc/src/mutex_pool.o"
	@echo "... jemalloc/src/mutex_pool.i"
	@echo "... jemalloc/src/mutex_pool.s"
	@echo "... jemalloc/src/nstime.o"
	@echo "... jemalloc/src/nstime.i"
	@echo "... jemalloc/src/nstime.s"
	@echo "... jemalloc/src/pages.o"
	@echo "... jemalloc/src/pages.i"
	@echo "... jemalloc/src/pages.s"
	@echo "... jemalloc/src/prng.o"
	@echo "... jemalloc/src/prng.i"
	@echo "... jemalloc/src/prng.s"
	@echo "... jemalloc/src/prof.o"
	@echo "... jemalloc/src/prof.i"
	@echo "... jemalloc/src/prof.s"
	@echo "... jemalloc/src/rtree.o"
	@echo "... jemalloc/src/rtree.i"
	@echo "... jemalloc/src/rtree.s"
	@echo "... jemalloc/src/stats.o"
	@echo "... jemalloc/src/stats.i"
	@echo "... jemalloc/src/stats.s"
	@echo "... jemalloc/src/sz.o"
	@echo "... jemalloc/src/sz.i"
	@echo "... jemalloc/src/sz.s"
	@echo "... jemalloc/src/tcache.o"
	@echo "... jemalloc/src/tcache.i"
	@echo "... jemalloc/src/tcache.s"
	@echo "... jemalloc/src/ticker.o"
	@echo "... jemalloc/src/ticker.i"
	@echo "... jemalloc/src/ticker.s"
	@echo "... jemalloc/src/tsd.o"
	@echo "... jemalloc/src/tsd.i"
	@echo "... jemalloc/src/tsd.s"
	@echo "... jemalloc/src/witness.o"
	@echo "... jemalloc/src/witness.i"
	@echo "... jemalloc/src/witness.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

